# Generated by Django 2.1.7 on 2019-02-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0008_merge_20190216_2024'),
        ('tickets', '0004_auto_20181214_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('attendants', models.ManyToManyField(to='tickets.Attendant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
