# Generated by Django 2.1.7 on 2019-02-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190219_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='attendants',
            field=models.ManyToManyField(blank=True, null=True, to='tickets.Attendant'),
        ),
    ]
