# Generated by Django 2.1.7 on 2019-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190221_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='attendants',
            field=models.ManyToManyField(blank=True, to='tickets.Attendant'),
        ),
    ]
