# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='commentary',
            field=models.TextField(null=True),
        ),
    ]
