# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20180306_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Validator'),
        ),
    ]
