# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_auto_20180307_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Validator'),
        ),
    ]
