# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_remove_volunteer_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='rolelist',
            field=models.ManyToManyField(to='volunteers.VolunteerRole'),
        ),
    ]
