# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_auto_20180308_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='rolelist',
            field=models.ManyToManyField(blank=True, editable=False, to='volunteers.VolunteerRole'),
        ),
    ]
