# Generated by Django 2.1.4 on 2018-12-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_auto_20180313_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Degree'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.School'),
        ),
        migrations.AlterField(
            model_name='volunteerschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteers.Schedule'),
        ),
    ]
