# Generated by Django 2.1.5 on 2019-02-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20181214_0113'),
        ('volunteers', '0012_auto_20181214_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='expedient',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='identity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='tickets.Attendant'),
        ),
    ]
