# Generated by Django 2.1.7 on 2019-02-14 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0013_auto_20190204_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='school',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='surname',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='identity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.Attendant'),
        ),
    ]
