# Generated by Django 2.1.7 on 2019-02-14 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0014_auto_20190214_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tickets.Attendant'),
        ),
    ]
