# Generated by Django 2.1.7 on 2019-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0017_remove_schedule_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerschedule',
            name='schedule',
            field=models.CharField(choices=[('Mañana', 'Morning'), ('Tarde', 'Afternoon')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
