# Generated by Django 2.1.7 on 2019-02-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0019_auto_20190216_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='rolelist',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='rolelist',
            field=models.ManyToManyField(blank=True, editable=False, to='volunteers.VolunteerRole'),
        ),
        migrations.AlterField(
            model_name='volunteerschedule',
            name='schedule',
            field=models.CharField(choices=[('M', 'Morning'), ('T', 'Afternoon')], max_length=20),
        ),
    ]
