# Generated by Django 2.1.7 on 2019-03-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20190315_1921'),
        ('volunteers', '0020_auto_20190221_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='rolelist',
        ),
        migrations.AlterField(
            model_name='volunteerschedule',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Attendant'),
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
