# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logosCompanys')),
                ('url', models.URLField(blank=True)),
                ('url_cv', models.URLField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('google_calendar_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes')),
                ('hide', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('companies', models.ManyToManyField(blank=True, to='editions.Company')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='editions.Edition')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='speakers')),
                ('personal_web', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('twitter_profile', models.URLField(blank=True)),
                ('facebook_profile', models.URLField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('googleplus_profile', models.URLField(blank=True)),
                ('github_profile', models.URLField(blank=True)),
                ('gitlab_profile', models.URLField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('room', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.SessionFormat'),
        ),
        migrations.AddField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='editions.Speaker'),
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ManyToManyField(blank=True, to='editions.Track'),
        ),
        migrations.AddField(
            model_name='prize',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Session'),
        ),
    ]
