# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_prize_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes')),
            ],
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='partner',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='image',
        ),
        migrations.AddField(
            model_name='prize',
            name='prize_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.PrizeObject'),
        ),
    ]
