# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0003_auto_20180315_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='slide',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sponsor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.SponsorType'),
        ),
    ]
