# Generated by Django 2.1.4 on 2018-12-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0004_auto_20180315_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='editions.Company'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='editions.PrizeObject'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Session'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.Attendant'),
        ),
        migrations.AlterField(
            model_name='session',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='editions.Edition'),
        ),
        migrations.AlterField(
            model_name='session',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='editions.SessionFormat'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='editions.Company'),
        ),
    ]
