# Generated by Django 2.1.4 on 2019-01-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0005_auto_20181214_0113'),
        ('editions', '0005_auto_20181113_0013'),
    ]

    operations = [
    ]
