# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-13 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0005_auto_20181113_0013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companysponsortype',
            table='editions_company_sponsortype',
        ),
    ]
