# Generated by Django 2.1.4 on 2019-01-30 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0006_merge_20190130_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysponsortype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Company'),
        ),
        migrations.AlterField(
            model_name='companysponsortype',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Edition'),
        ),
        migrations.AlterField(
            model_name='companysponsortype',
            name='sponsor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.SponsorType'),
        ),
        migrations.AlterModelTable(
            name='companysponsortype',
            table='editions_company_sponsortype',
        ),
    ]
