# Generated by Django 2.1.7 on 2019-02-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0007_auto_20190130_2343'),
        ('editions', '0006_auto_20181113_2009'),
    ]

    operations = [
    ]
