# Generated by Django 2.1.7 on 2019-02-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0008_merge_20190216_2024'),
        ('editions', '0008_merge_20190214_1955'),
    ]

    operations = [
    ]
