# Generated by Django 2.1.7 on 2020-02-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0009_merge_20190221_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('linkedin', models.URLField()),
            ],
        ),
    ]
