# Generated by Django 2.1.7 on 2020-02-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0011_organizer_edition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='image',
            new_name='picture',
        ),
    ]
