# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('sponsor', models.BooleanField(default=False)),
                ('sponsor_type', models.CharField(blank=True, choices=[('oro', 'ORO'), ('plata', 'PLATA'), ('bronce', 'BRONCE')], max_length=50)),
                ('sponsor_date', models.CharField(blank=True, choices=[('19/03/2018', '19/03/2018'), ('20/03/2018', '20/03/2018'), ('21/03/2018', '21/03/2018'), ('22/03/2018', '22/03/2018')], max_length=50)),
                ('type', models.CharField(choices=[('ponencia', 'Ponencia'), ('taller', 'Taller')], default='ponencia', max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
    ]
