# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercompany',
            name='sponsor_date',
            field=models.CharField(blank=True, choices=[('18/03/2019', '18/03/2019'), ('19/03/2019', '19/03/2019'), ('20/03/2019', '20/03/2019'), ('21/03/2019', '21/03/2019'), ('22/03/2019', '22/03/2019')], max_length=50),
        ),
    ]
