# Generated by Django 2.1.7 on 2020-02-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20181112_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercompany',
            name='sponsor_date',
            field=models.CharField(blank=True, choices=[('16/03/2020', '16/03/2020'), ('17/03/2020', '17/03/2020'), ('18/03/2020', '18/03/2020'), ('19/03/2020', '19/03/2020'), ('20/03/2020', '20/03/2020')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registercompany',
            name='sponsor_type',
            field=models.CharField(blank=True, choices=[('platino', 'PLATINO'), ('oro', 'ORO'), ('plata', 'PLATA'), ('bronce', 'BRONCE')], max_length=50),
        ),
    ]
