# Generated by Django 2.1.7 on 2019-03-16 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0009_merge_20190221_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Edition')),
            ],
        ),
    ]
