# Generated by Django 2.2.1 on 2021-03-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_attendant_student_id'),
        ('editions', '0012_auto_20200225_2152'),
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Attendant')),
                ('slot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='congress.AttendanceSlot')),
            ],
            options={
                'unique_together': {('attendant', 'slot')},
            },
        ),
    ]
