# Generated by Django 2.1.7 on 2019-11-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0009_merge_20190221_1719'),
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('edition', models.ManyToManyField(to='editions.Edition')),
            ],
        ),
    ]
