# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_attachment_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='title',
        ),
    ]
