# Generated by Django 2.1.7 on 2020-02-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0011_organizer_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Company')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Edition')),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsorship.Sponsorship'),
        ),
    ]
