# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('student', models.BooleanField(default=False)),
                ('upm_student', models.BooleanField(default=False)),
                ('college', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('identity', models.CharField(blank=True, max_length=9)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Attendant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('secret_key', models.CharField(editable=False, max_length=16)),
                ('signature', models.CharField(blank=True, editable=False, max_length=256)),
                ('attendant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.Attendant')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('available_amount', models.PositiveIntegerField(default=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Edition')),
                ('session_formats', models.ManyToManyField(blank=True, to='editions.SessionFormat')),
                ('sessions', models.ManyToManyField(blank=True, to='editions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret_key', models.CharField(editable=False, max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketType'),
        ),
        migrations.AddField(
            model_name='degree',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.School'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Validator'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together=set([('attendant', 'session')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendant',
            unique_together=set([('edition', 'email')]),
        ),
    ]
