# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_remove_volunteer_validator'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='volunteer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
