# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180308_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
