# Generated by Django 2.1.4 on 2018-12-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180315_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Edition'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Attendant'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Session'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Validator'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.School'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attendant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tickets.Attendant'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.TicketType'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editions.Edition'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='volunteer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Volunteer'),
        ),
    ]
