# Generated by Django 2.1.7 on 2019-02-15 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190215_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Volunteer', unique=True),
        ),
    ]
