# Generated by Django 2.1.7 on 2019-02-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190216_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Volunteer', unique=True),
        ),
    ]
