# Generated by Django 2.1.7 on 2019-03-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0020_auto_20190221_1720'),
        ('tickets', '0009_auto_20190221_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendant',
            name='android_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendant',
            name='commentary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attendant',
            name='rolelist',
            field=models.ManyToManyField(blank=True, editable=False, to='volunteers.VolunteerRole'),
        ),
        migrations.AddField(
            model_name='attendant',
            name='shirt_size',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='m', max_length=250),
        ),
        migrations.AlterField(
            model_name='validator',
            name='volunteer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.Attendant'),
        ),
    ]
