# Generated by Django 2.1.7 on 2019-03-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20190315_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='registered_as_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
