# Generated by Django 2.1.7 on 2020-02-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_attendant_registered_as_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendant',
            old_name='student',
            new_name='is_student',
        ),
        migrations.RenameField(
            model_name='attendant',
            old_name='is_upm_student',
            new_name='is_upm_student',
        ),
    ]
