# Generated by Django 2.1.7 on 2019-03-22 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_attendant_ects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='ects',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
    ]
