# Generated by Django 2.1.7 on 2020-02-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20200207_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='print_accreditation',
            field=models.BooleanField(default=False),
        ),
    ]
