# Generated by Django 2.2.1 on 2021-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_attendant_print_accreditation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='student_id',
            field=models.CharField(default='y160242', max_length=200),
            preserve_default=False,
        ),
    ]
